apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-eks-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-eks-gitops
  template:
    metadata:
      labels: # tag 
        app: go-eks-gitops
    spec:
      containers:
      - name: go-eks-gitops
        image: harshal0001/go-eks-gitops 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
