apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-eks-gitops
  annotation:
   nginx.ingress.kubernetes.io/rewrite-target
spec:
  ingressClassName: nginx
  rules:
  - host: joshiharshal.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-web-app
            port: 
              number: 8080
