apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-eks-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: gitops.joshiharshal.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-eks-gitops
                port:
                  number: 80
